# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ff96fa8cc99cfc6e1cd33f2c1e99c8d82e36401bbdc61ae6481c114f610c5ba16dd81f1c0d01145dffd217601ee9f0e13cbb8d02889ed29ad35b8d2090263fd

test:
  secret_key_base: b14db83e3c8781256e3c3a956a34fa63842c0d6071fa98d5e6577b706c9256c246210750d508aee4b5f1e463020b6ff993fe29cbc4f68b857b19726c601089b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
